const db = [
  {
    id: 1,
    first_name: "Bink",
    last_name: "Barthod",
    email: "bbarthod0@gmpg.org",
    gender: "Male",
    status: "Married",
    img: "https://randomuser.me/api/portraits/men/1.jpg",
    created_at: "20-06-2022",
  },
  {
    id: 2,
    first_name: "Celinda",
    last_name: "Urpeth",
    email: "curpeth1@shutterfly.com",
    gender: "Female",
    status: "Single",
    img: "https://randomuser.me/api/portraits/women/1.jpg",
    created_at: "20-06-2022",
  },
  {
    id: 3,
    first_name: "John",
    last_name: "Armall",
    email: "jarmall2@themeforest.net",
    gender: "Male",
    status: "Single",
    img: "https://randomuser.me/api/portraits/men/2.jpg",
    created_at: "20-09-2022",
  },
  {
    id: 4,
    first_name: "Cam",
    last_name: "Malyj",
    email: "cmalyj3@globo.com",
    gender: "Male",
    status: "Married",
    img: "https://randomuser.me/api/portraits/men/3.jpg",
    created_at: "20-10-2022",
  },
  {
    id: 5,
    first_name: "Gertrud",
    last_name: "Groundwator",
    email: "ggroundwator4@diigo.com",
    gender: "Male",
    status: "Single",
    img: "https://randomuser.me/api/portraits/men/4.jpg",
    created_at: "20-10-2022",
  },
  {
    id: 6,
    first_name: "Leupold",
    last_name: "Rown",
    email: "lrown5@dailymail.co.uk",
    gender: "Male",
    status: "Single",
    img: "https://randomuser.me/api/portraits/men/5.jpg",
    created_at: "06-10-2022",
  },
  {
    id: 7,
    first_name: "Cara",
    last_name: "Mercik",
    email: "cmercik6@stanford.edu",
    gender: "Female",
    status: "Married",
    img: "https://randomuser.me/api/portraits/women/2.jpg",
    created_at: "20-08-2022",
  },
  {
    id: 8,
    first_name: "Monique",
    last_name: "D'Avaux",
    email: "mdavaux7@yellowpages.com",
    gender: "Female",
    status: "Married",
    img: "https://randomuser.me/api/portraits/women/3.jpg",
    created_at: "20-08-2022",
  },
  {
    id: 9,
    first_name: "Orin",
    last_name: "Battabee",
    email: "obattabee8@nature.com",
    gender: "Male",
    status: "Married",
    img: "https://randomuser.me/api/portraits/men/6.jpg",
    created_at: "12-08-2022",
  },
  {
    id: 10,
    first_name: "Carey",
    last_name: "Lassen",
    email: "classen9@csmonitor.com",
    gender: "Male",
    status: "Married",
    img: "https://randomuser.me/api/portraits/men/7.jpg",
    created_at: "20-03-2022",
  },
  {
    id: 11,
    first_name: "Brant",
    last_name: "Hinrichs",
    email: "bhinrichsa@fda.gov",
    gender: "Female",
    status: "Married",
    img: "https://randomuser.me/api/portraits/women/4.jpg",
    created_at: "20-03-2022",
  },
  {
    id: 12,
    first_name: "Mal",
    last_name: "Pitrelli",
    email: "mpitrellib@weather.com",
    gender: "Male",
    status: "Married",
    img: "https://randomuser.me/api/portraits/men/8.jpg",
    created_at: "14-03-2022",
  },
  {
    id: 13,
    first_name: "Georgi",
    last_name: "Bushel",
    email: "gbushelc@dyndns.org",
    gender: "Male",
    status: "Married",
    img: "https://randomuser.me/api/portraits/men/9.jpg",
    created_at: "10-03-2022",
  },
  {
    id: 14,
    first_name: "Ali",
    last_name: "Wearden",
    email: "aweardend@printfriendly.com",
    gender: "Male",
    status: "Single",
    img: "https://randomuser.me/api/portraits/men/10.jpg",
    created_at: "20-03-2022",
  },
  {
    id: 15,
    first_name: "Bettye",
    last_name: "Busk",
    email: "bbuske@themeforest.net",
    gender: "Female",
    status: "Single",
    img: "https://randomuser.me/api/portraits/women/5.jpg",
    created_at: "18-10-2022",
  },
  {
    id: 16,
    first_name: "Wes",
    last_name: "Terry",
    email: "wterryf@cbslocal.com",
    gender: "Male",
    status: "Single",
    img: "https://randomuser.me/api/portraits/men/11.jpg",
    created_at: "12-03-2022",
  },
  {
    id: 17,
    first_name: "Nicolai",
    last_name: "Clamo",
    email: "nclamog@businessweek.com",
    gender: "Male",
    status: "Single",
    img: "https://randomuser.me/api/portraits/men/15.jpg",
    created_at: "15-03-2022",
  },
  {
    id: 18,
    first_name: "Ruprecht",
    last_name: "Aldus",
    email: "raldush@weibo.com",
    gender: "Male",
    status: "Married",
    img: "https://randomuser.me/api/portraits/men/12.jpg",
    created_at: "15-03-2022",
  },
  {
    id: 19,
    first_name: "Colver",
    last_name: "Stenson",
    email: "cstensoni@merriam-webster.com",
    gender: "Male",
    status: "Single",
    img: "https://randomuser.me/api/portraits/men/13.jpg",
    created_at: "15-03-2022",
  },
  {
    id: 20,
    first_name: "Leonid",
    last_name: "Patrickson",
    email: "lpatricksonj@imageshack.us",
    gender: "Male",
    status: "Married",
    img: "https://randomuser.me/api/portraits/men/14.jpg",
    created_at: "19-10-2022",
  },
  {
    id: 21,
    first_name: "Lemuel",
    last_name: "McNerlin",
    email: "lmcnerlink@icio.us",
    gender: "Male",
    status: "Married",
    img: "https://randomuser.me/api/portraits/men/16.jpg",
    created_at: "15-03-2022",
  },
  {
    id: 22,
    first_name: "Tiler",
    last_name: "Hibling",
    email: "thiblingl@examiner.com",
    gender: "Male",
    status: "Single",
    img: "https://randomuser.me/api/portraits/men/17.jpg",
    created_at: "12-08-2022",
  },
  {
    id: 23,
    first_name: "Care",
    last_name: "Crown",
    email: "ccrownm@washington.edu",
    gender: "Male",
    status: "Single",
    img: "https://randomuser.me/api/portraits/men/18.jpg",
    created_at: "18-10-2022",
  },
  {
    id: 24,
    first_name: "Sile",
    last_name: "Bowden",
    email: "sbowdenn@prnewswire.com",
    gender: "Female",
    status: "Married",
    img: "https://randomuser.me/api/portraits/women/6.jpg",
    created_at: "12-08-2022",
  },
  {
    id: 25,
    first_name: "Andonis",
    last_name: "Deely",
    email: "adeelyo@histats.com",
    gender: "Female",
    status: "Married",
    img: "https://randomuser.me/api/portraits/women/7.jpg",
    created_at: "10-03-2022",
  },
  {
    id: 26,
    first_name: "Cassie",
    last_name: "Adelman",
    email: "cadelmanp@utexas.edu",
    gender: "Female",
    status: "Married",
    img: "https://randomuser.me/api/portraits/women/9.jpg",
    created_at: "12-08-2022",
  },
  {
    id: 27,
    first_name: "Pancho",
    last_name: "Bergstram",
    email: "pbergstramq@posterous.com",
    gender: "Female",
    status: "Married",
    img: "https://randomuser.me/api/portraits/women/10.jpg",
    created_at: "18-10-2022",
  },
  {
    id: 28,
    first_name: "Ody",
    last_name: "Tuer",
    email: "otuerr@vinaora.com",
    gender: "Male",
    status: "Married",
    img: "https://randomuser.me/api/portraits/men/19.jpg",
    created_at: "12-08-2022",
  },
  {
    id: 29,
    first_name: "Joey",
    last_name: "Bartoszek",
    email: "jbartoszeks@issuu.com",
    gender: "Female",
    status: "Married",
    img: "https://randomuser.me/api/portraits/women/11.jpg",
    created_at: "12-08-2022",
  },
  {
    id: 30,
    first_name: "Harmonia",
    last_name: "Cominoli",
    email: "hcominolit@gizmodo.com",
    gender: "Female",
    status: "Married",
    img: "https://randomuser.me/api/portraits/women/13.jpg",
    created_at: "19-10-2022",
  },
];

module.exports = db;
